version: '3.8'

services:
  # Frontend Service
  discordgym-ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - discordgym-network
    depends_on:
      - discordgym-api

  # Backend Service  
  discordgym-api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://discordgym:discordgym123@db:3306/discordgym
      - JWT_SECRET=DgSecure2024!JWT#Secret$Random%Token&Key*2025
      - JWT_REFRESH_SECRET=DgRefresh2024!JWT#Secret$Random%Token&Key*2025
    volumes:
      # Delegated volumes f端r bessere Performance auf Mac
      - ./server:/app:delegated
      - /app/node_modules
    restart: unless-stopped
    networks:
      - discordgym-network
    depends_on:
      - db
      - redis

  # Database Service
  db:
    image: mariadb:10.11
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=discordgym
      - MARIADB_USER=discordgym
      - MARIADB_PASSWORD=discordgym123
    ports:
      - "3307:3306"
    volumes:
      # Named volume f端r bessere DB-Performance
      - discordgym_db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - discordgym-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  # Redis Service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      # Named volume f端r Redis-Persistenz
      - discordgym_redis_data:/data
    restart: unless-stopped
    networks:
      - discordgym-network
    command: redis-server --appendonly yes

  # Prisma Studio
  prisma-studio:
    build:
      context: ./server
      dockerfile: Dockerfile.prisma
    ports:
      - "5556:5555"
    environment:
      - DATABASE_URL=mysql://discordgym:discordgym123@db:3306/discordgym
    volumes:
      - ./server:/app:delegated
      - /app/node_modules
    restart: unless-stopped
    networks:
      - discordgym-network
    depends_on:
      - db

networks:
  discordgym-network:
    driver: bridge

volumes:
  # Named volumes f端r bessere Performance auf Mac
  discordgym_db_data:
    driver: local
  discordgym_redis_data:
    driver: local
